---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-appcontainer
        image: your_frontend_docker
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc
spec:
  type: NodePort  # Or LoadBalancer, depending on your setup
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80       # Port that the service exposes (can be different from the container port)
      targetPort: 4200 # Port the application listens on inside the container
      nodePort: 30001  # Port exposed on each node (between 30000 and 32767)